UPDATE fieldkit.sensor_meta SET viz = '[{"name":"D3TimeSeriesGraph","disabled":false,"minimumGap":86400,"thresholds":null}]'::json WHERE full_key IN (
    'fk.weather.humidity',
    'fk.weather.pressure',
    'fk.weather.temperature1',
    'fk.weather.temperature2',

    'fk.water.temp.temp',
    'fk.water.ph.ph',
    'fk.water.orp.orp',
    'fk.water.ec.ec',
    'fk.water.do.do',
    'fk.water.do.pressure',
    'fk.water.do.temperature',

    'fk.water.ms5837.depth',
    'fk.water.ms5837.temp',

    'fk.weather.rain',
    'fk.weather.rainPrevHour',
    'fk.weather.rainThisHour',

    'fk.weather.wind',
    'fk.weather.wind10mMaxDir',
    'fk.weather.wind10mMaxSpeed',
    'fk.weather.wind2mAvgDir',
    'fk.weather.wind2mAvgSpeed',
    'fk.weather.windDir',
    'fk.weather.windDirMv',
    'fk.weather.windHrMaxDir',
    'fk.weather.windHrMaxSpeed',
    'fk.weather.windMv',
    'fk.weather.windSpeed',

    'fk.distance.distance',
    'fk.distance.calibration',
    'fk.distance.distance0',
    'fk.distance.distance1',
    'fk.distance.distance2',
    
    'fk.diagnostics.batteryCharge',
    'fk.diagnostics.batteryMa',
    'fk.diagnostics.batteryPower',
    'fk.diagnostics.batteryVbus',
    'fk.diagnostics.batteryVoltage',
    'fk.diagnostics.batteryVs',
    'fk.diagnostics.freeMemory',
    'fk.diagnostics.solarMa',
    'fk.diagnostics.solarPower',
    'fk.diagnostics.solarVbus',
    'fk.diagnostics.solarVs',
    'fk.diagnostics.temperature',
    'fk.diagnostics.uptime',
    'fk.diagnostics.batteryVoltage'
);
