/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.ArrayList;

import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.FileOutputStream;

import java.net.MalformedURLException;
import java.net.URL;

import java.security.interfaces.RSAPublicKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;

import org.example.WiFi101Certificate;
import org.example.WiFi101CertificateBundle;

public class App {
    public static void main(String[] args) throws Exception {
        List<String> sources= new ArrayList<String>();
        sources.add("https://api.fieldkit.org"); // Amazon CA
        sources.add("https://valid-isrgrootx1.letsencrypt.org/");
    
        WiFi101CertificateBundle bundle = createBundleFromWebsites(sources);

        System.out.println("writing ssl-v0.bin");
        try (FileOutputStream stream = new FileOutputStream("ssl-v0.bin")) {
            stream.write(bundle.getEncodedV0());
        }

        System.out.println("writing ssl-v1.bin");
        try (FileOutputStream stream = new FileOutputStream("ssl-v1.bin")) {
            stream.write(bundle.getEncodedV1());
        }
    }
    
    public static WiFi101CertificateBundle createBundleFromWebsites(List<String> urls) throws Exception {
    		WiFi101CertificateBundle bundle = new WiFi101CertificateBundle();
    		for (String site : urls) {
            URL url =  new URL(site);
            Certificate[] certificates = SSLCertDownloader.retrieveFromURL(url);
            for (int i = certificates.length - 1; i >= 0; i--) {
                X509Certificate x509 = (X509Certificate) certificates[i];
                if (x509.getPublicKey() instanceof RSAPublicKey) {
                    System.out.println(site + " " + x509.getPublicKey());
                    System.out.println("");
                    System.out.println("");
                    bundle.add(new WiFi101Certificate(x509));
                    break;
                }
            }
        }
        return bundle;
    }
}
