#!/bin/bash

BOOTLOADER=fkbl-fkb.bin
PROGRAM=fk-bundled-fkb.bin

JLinkExe -if SWD -device ATSAMD51P20 -speed 4000 <<EOF
exitonerror 1
connect
h
exec SetRTTSearchRanges 0x20000000 64
sleep 100
r
sleep 100
loadfile $BOOTLOADER,0x00000
sleep 100
loadfile $BOOTLOADER,0x80000
sleep 100
loadfile $PROGRAM,0x08000
sleep 100
loadfile $PROGRAM,0x88000
sleep 100
r
sleep 100
go
q
EOF
